version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: colmeia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: colmeia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - colmeia_network

volumes:
  postgres_data:

networks:
  colmeia_network:
    driver: bridge
